In [1]:
import torch

In [25]:
data = [[1.4,2.4],[3.4,4.4]]

In [33]:
x_data = torch.tensor(data)

In [34]:
x_data.type()

'torch.FloatTensor'

In [35]:
data[0]

[1.4, 2.4]

In [36]:
import numpy as np

In [37]:
np_array = np.array(data)

In [38]:
x_np = torch.from_numpy(np_array)

In [39]:
x_np.type()

'torch.DoubleTensor'

In [87]:
a = torch.ones(4,4)

In [88]:
n = a.numpy()

In [90]:
a = a.add(1)

In [91]:
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [92]:
a

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [94]:
np.add(n, 1, out=n)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)